# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_name',
            new_name='username',
        ),
    ]
